### ISSUE TITLE
How to authorize application to copy images from single project to multiple google projects using user account?

### ISSUE THREAD

**Issue by amv93** [google/nodejs-container-image-builder#38]
I have a project from which I want to copy few container images to another project using a node application. I use container-image-builder module for the same. 
The copying works with service account credentials,but I want to use user account credentials. The Oauth credentials allow only copying of images within the project but not across multiple google projects as OAuth credentials restricts to a single project per application.
Is there any other way that would allow me to use user account to accomplish this provided the user account has appropriate permissions?

**Comment by soldair** [comment]
hey this is a bug! right now authentication is held in a single key for gcr.io and the same auth client is reused!

I intend to fix this asap. thanks so much for the report

**Comment by soldair** [comment]
landed fix for this in version 3.0.0

**Comment by soldair** [comment]
added section in the readme 
https://github.com/google/nodejs-container-image-builder#authenticating-to-multiple-gcr-projects

and working example 
https://github.com/google/nodejs-container-image-builder/blob/master/example/multiple-gcr.js
