### ISSUE TITLE
Parse the hierarchical structure of the image 

### ISSUE THREAD

**Issue by amv93** [google/nodejs-container-image-builder#42]
If the image is of the form 'gcr.io/myFirstProject/images/hello-world' then the parser will leave out 'myFirstProject'
image= 'hello-world'
namespace='images'
registry='gcr.io'
 https://github.com/google/nodejs-container-image-builder/blob/9e85d2fbb44d09f31aa73bdb98479ede879757c7/src/image-specifier.ts#L30

**Comment by soldair** [comment]
nice catch. I wasn't aware slashes were allowed in image names.
let you know when i have a fix =)

**Comment by soldair** [comment]
relevant. 
https://github.com/google/ko#ko-resolve it seems like dockerhub doesn't have support for "multi-level repository names"

this likely doesn't impact the kind of fix we need to use

**Comment by soldair** [comment]
published to npm in 3.1.0

**Comment by soldair** [comment]
we may need to add url escaping on the namespace for api calls in src/registry.ts for this to really work but this is the big part
