### ISSUE TITLE
Is it possbile to support only passing only access token in Image API for gcloud images?

### ISSUE THREAD

**Issue by amv93** [google/nodejs-container-image-builder#45]
I understand that authentication to gcr is done with the google-auth-client npm package. the options  are defined here: https://github.com/googleapis/google-auth-library-nodejs/blob/master/src/auth/googleauth.ts#L64, but is it possible to send the the token directly to the Image API?

**Comment by soldair** [comment]
yes it seems the example at the top of the doc is wrong. authentication for registries is passed into the auth key of the options passed to the image constructor

```
const image = new Image('node:lts-slim','myspecialregistry.io/my-project/my-image',{
   auth:{
      'myspecialregistry.io':{
        token:"xxxxxxxxxxx"
      }
    }
})
```
there is much more  information about auth in the documentation now thanks to your other issues =)
